### ISSUE TITLE
Project feedback

### ISSUE THREAD

**Issue by adamstep** [yogsma/team-management#3]
Hi @yogsma , I was not able to get the backend running after following the steps. I get stuck trying to run migrate or runserver:

```
(env) ~/projects/take-homes/yogsma/team-management/backend (main) $ python manage.py migrate  
Traceback (most recent call last):
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/core/management/base.py", line 103, in wrapper
    saved_locale = translation.get_language()
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 210, in get_language
    return _trans.get_language()
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 65, in __getattr__
    if settings.USE_I18N:
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/adam/.pyenv/versions/3.10.9/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'project'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/manage.py", line 22, in <module>
    main()
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/core/management/base.py", line 425, in run_from_argv
    connections.close_all()
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/utils/connection.py", line 84, in close_all
    for conn in self.all(initialized_only=True):
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/utils/connection.py", line 76, in all
    return [
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/db/utils.py", line 148, in configure_settings
    databases = super().configure_settings(databases)
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/adam/projects/take-homes/yogsma/team-management/backend/env/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/adam/.pyenv/versions/3.10.9/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'project'
```

**Comment by yogsma** [comment]
@adamstep - Thanks for the feedback. I am wondering if it has anything to do with python version. It works perfectly fine for python 3.8. Let me try for python 3.10

**Comment by yogsma** [comment]
@adamstep - I ran all the steps on python 3.10 and didn't see any errors.

**Comment by yogsma** [comment]
Can this resolution help https://forum.djangoproject.com/t/modulenotfound-error/22434?

**Comment by adamstep** [comment]
Thanks, I was able to get it to work now. I have some feedback on the project:
- When I delete a member, there's no confirmation before the action happens. Ideally there's a confirmation dialog before that lets me cancel or proceed.
- When I enter invalid phone number or email, I get a generic error even though the response contains specifics about the field. It would be better to show inline error messages from the server.

Let me know if you're able to make these changes, thanks1

**Comment by yogsma** [comment]
Thanks @adamstep . I added the changes https://github.com/yogsma/team-management/pull/4
